version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    container_name: frontend_TAA
    restart: always
    depends_on:
      - backend

  db:
    container_name: db_TAA
    image: mysql:8.0.18
    environment:
      MYSQL_DATABASE: db_week_end
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    restart: always

  backend:
    restart: always
    build: .
    container_name: backend
    command: ["./wait-for-mysql.sh"]
    ports:
      - "8080:8888"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=db_week_end
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/db_week_end
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
